language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t atmakurikirankumar/simple-react-app -f Dockerfile .

script:
  - docker run -e CI=true atmakurikirankumar/simple-react-app

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "simple-react-app"
  env: "SimpleReactApp-env"
  bucket_name: "elasticbeanstalk-us-east-1-996637240614"
  bucket_path: "simple-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
