version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.Dev
    restart: on-failure
    container_name: "simple-react-app"
    stdin_open: true
    volumes:
      - /usr/app/node_modules
      - ./:/usr/app/
    ports:
      - "3000:3000"
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    volumes:
      - /usr/app/node_modules
      - ./:/usr/app/
    command: ["npm", "run", "test"]
